apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nodeapi
  name: nodeapi
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nodeapi
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodeapi
    spec:
      containers:
      - image: 70d3f4721900
        name: node-api
        imagePullPolicy: Never
        resources: {}
        ports:
          - containerPort: 3000 
status: {}